sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test

after_success:
  - docker build -t cmkjani/multi-client ./client
  - docker build -t cmkjani/multi-nginx ./nginx
  - docker build -t cmkjani/multi-server ./server
  - docker build -t cmkjani/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push docker images
  - docker push cmkjani/multi-client
  - docker push cmkjani/multi-nginx
  - docker push cmkjani/multi-server
  - docker push cmkjani/multi-worker
